---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.executor_name }}-{{ .Values.env }}
  name: prometheus-am-executor
spec:
  ports:
  - name: "executor-port"
    port: 8020
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Values.executor_name }}-{{ .Values.env }}