# Generated by Terraform in pre-deploy - do not modify manually!

resource_group_name  = "terraform"
storage_account_name = "eydev034"
container_name       = "terraform-eydev34"
key                  = "eydev34.terraform.tfstate"
