# Generated by Terraform in pre-deploy - do not modify manually!

resource_group_name  = "terraform"
storage_account_name = "eydev038"
container_name       = "terraform-eydev38"
key                  = "eydev38.terraform.tfstate"
