# Generated by Terraform in pre-deploy - do not modify manually!

resource_group_name  = "terraform"
storage_account_name = "eydev019"
container_name       = "terraform-eydev19"
key                  = "eydev19.terraform.tfstate"
