# Generated by Terraform in pre-deploy - do not modify manually!

resource_group_name  = "terraform"
storage_account_name = "eydev030"
container_name       = "terraform-eydev30"
key                  = "eydev30.terraform.tfstate"
