# Generated by Terraform in pre-deploy - do not modify manually!

resource_group_name  = "terraform"
storage_account_name = "eydev051"
container_name       = "terraform-eydev51"
key                  = "eydev51.terraform.tfstate"
