# Generated by Terraform in pre-deploy - do not modify manually!

resource_group_name  = "terraform"
storage_account_name = "eydev033"
container_name       = "terraform-eydev33"
key                  = "eydev33.terraform.tfstate"
