# Generated by Terraform in pre-deploy - do not modify manually!

resource_group_name  = "terraform"
storage_account_name = "eydev029"
container_name       = "terraform-eydev029"
key                  = "eydev029.terraform.tfstate"
