# Generated by Terraform in pre-deploy - do not modify manually!

resource_group_name  = "terraform"
storage_account_name = "eydev050"
container_name       = "terraform-eydev50"
key                  = "eydev50.terraform.tfstate"
