# Generated by Terraform in pre-deploy - do not modify manually!

resource_group_name  = "terraform"
storage_account_name = "eydev06"
container_name       = "terraform-eydev006"
key                  = "eydev006.terraform.tfstate"
