# Generated by Terraform in pre-deploy - do not modify manually!

resource_group_name  = "terraform"
storage_account_name = "eydev045"
container_name       = "terraform-eydev45"
key                  = "eydev45.terraform.tfstate"
