# Generated by Terraform in pre-deploy - do not modify manually!

resource_group_name  = "terraform"
storage_account_name = "eydev046"
container_name       = "terraform-eydev46"
key                  = "eydev46.terraform.tfstate"
