# Generated by Terraform in pre-deploy - do not modify manually!

resource_group_name  = "terraform"
storage_account_name = "eydev020"
container_name       = "terraform-eydev20"
key                  = "eydev20.terraform.tfstate"
