# Generated by Terraform in pre-deploy - do not modify manually!

resource_group_name  = "terraform"
storage_account_name = "eydev048"
container_name       = "terraform-eydev48"
key                  = "eydev48.terraform.tfstate"
