# Generated by Terraform in pre-deploy - do not modify manually!

resource_group_name  = "terraform"
storage_account_name = "eydev018"
container_name       = "terraform-eydev18"
key                  = "eydev18.terraform.tfstate"
