# Generated by Terraform in pre-deploy - do not modify manually!

resource_group_name  = "terraform"
storage_account_name = "eydev043"
container_name       = "terraform-eydev43"
key                  = "eydev43.terraform.tfstate"
