# Generated by Terraform in pre-deploy - do not modify manually!

resource_group_name  = "terraform"
storage_account_name = "eydev026"
container_name       = "terraform-eydev26"
key                  = "eydev26.terraform.tfstate"
