# Generated by Terraform in pre-deploy - do not modify manually!

resource_group_name  = "terraform"
storage_account_name = "eydev052"
container_name       = "terraform-eydev52"
key                  = "eydev52.terraform.tfstate"
