# Generated by Terraform in pre-deploy - do not modify manually!

resource_group_name  = "terraform"
storage_account_name = "eydev024"
container_name       = "terraform-eydev24"
key                  = "eydev24.terraform.tfstate"
