# Generated by Terraform in pre-deploy - do not modify manually!

resource_group_name  = "terraform"
storage_account_name = "eydev0047"
container_name       = "terraform-eydev047"
key                  = "eydev047.terraform.tfstate"
