# Generated by Terraform in pre-deploy - do not modify manually!

resource_group_name  = "terraform"
storage_account_name = "eydev031"
container_name       = "terraform-eydev031"
key                  = "eydev031.terraform.tfstate"
