# Generated by Terraform in pre-deploy - do not modify manually!

resource_group_name  = "terraform"
storage_account_name = "eydev036"
container_name       = "terraform-eydev36"
key                  = "eydev36.terraform.tfstate"
