# Generated by Terraform in pre-deploy - do not modify manually!

resource_group_name  = "terraform"
storage_account_name = "eydev056"
container_name       = "terraform-eydev56"
key                  = "eydev56.terraform.tfstate"
