# Generated by Terraform in pre-deploy - do not modify manually!

resource_group_name  = "terraform"
storage_account_name = "eydev044"
container_name       = "terraform-eydev44"
key                  = "eydev44.terraform.tfstate"
