# Generated by Terraform in pre-deploy - do not modify manually!

resource_group_name  = "terraform"
storage_account_name = "eydev021"
container_name       = "terraform-eydev21"
key                  = "eydev21.terraform.tfstate"
