# Generated by Terraform in pre-deploy - do not modify manually!

resource_group_name  = "terraform"
storage_account_name = "eydev023"
container_name       = "terraform-eydev23"
key                  = "eydev23.terraform.tfstate"
