# Generated by Terraform in pre-deploy - do not modify manually!

resource_group_name  = "terraform"
storage_account_name = "eydev035"
container_name       = "terraform-eydev35"
key                  = "eydev35.terraform.tfstate"
