# Generated by Terraform in pre-deploy - do not modify manually!

resource_group_name  = "terraform"
storage_account_name = "eydev025"
container_name       = "terraform-eydev25"
key                  = "eydev25.terraform.tfstate"
