# Generated by Terraform in pre-deploy - do not modify manually!

resource_group_name  = "terraform"
storage_account_name = "eydev022"
container_name       = "terraform-eydev22"
key                  = "eydev22.terraform.tfstate"
