{
 "title": "Backend Status",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "backendapp",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{app=\"backendapp\"}"
    }
   ]
  },
  {
   "title": "Backend Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_success{app=~\"backend.*\"}",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "backendweb",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{app=\"backendweb\"}"
    }
   ]
  }
 ]
}