# Generated by Terraform in pre-deploy - do not modify manually!

resource_group_name  = "${resource_group}"
storage_account_name = "${storage_account}"
container_name       = "${storage_container}"
key                  = "${key}"
