---
{{- if .Values.adminwebappparameters }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-adminwebapp-parameters
data:
  {{- range $key, $val := .Values.adminwebappparameters }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}

