---
{{- if .Values.parameters }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-parameters
data:
  {{- range $key, $val := .Values.parameters }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}