---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-main
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format json_combined escape=json '{"proxy_protocol_addr": "$proxy_protocol_addr", "remote_addr": "$remote_addr", "proxy_add_x_forwarded_for": "$proxy_add_x_forwarded_for", "time_local": "$time_local", "request" : "$request", "status": "$status", "body_bytes_sent": "$body_bytes_sent", "http_referer":  "$http_referer", "http_user_agent": "$http_user_agent", "request_length" : "$request_length", "request_time": "$request_time", "upstream_addr": "$upstream_addr",  "upstream_response_length": "$upstream_response_length", "upstream_response_time": "$upstream_response_time", "upstream_status": "$upstream_status", "http_host": "$http_host", "host": "$host"}';

        access_log /dev/stdout json_combined;
        error_log /dev/stdout warn;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        gzip on;
        gzip_disable "msie6";
        gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript;

        include /etc/nginx/conf.d/*.conf;
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-addon
data:
  local.conf: |
    upstream upstream_server_backend {
      server {{ .Release.Name }}-backend:8000;
    }

    upstream upstream_server_admin {
      server {{ .Release.Name }}-adminwebapp:80;
    }

    server {
      listen 80;
      listen [::]:80 default_server ipv6only=on;
      server_name _;

      keepalive_timeout  65;
      client_max_body_size 100M;

      location / {
        proxy_pass http://upstream_server_admin;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_redirect off;
        proxy_set_header  X-Forwarded-Proto  $scheme;
        proxy_read_timeout 1200;
        proxy_connect_timeout 300;
      }

      location /api {
        proxy_pass http://upstream_server_backend;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_redirect off;
        proxy_set_header  X-Forwarded-Proto  $scheme;
        proxy_read_timeout 1200;
        proxy_connect_timeout 300;
      }

      location /admin {
        proxy_pass http://upstream_server_backend;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_redirect off;
        proxy_set_header  X-Forwarded-Proto  $scheme;
        proxy_read_timeout 1200;
        proxy_connect_timeout 300;
      }

      location /staticfiles {
        alias /staticfiles;
      }

    }