---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.nginxweb.name }}-{{ .Values.env }}
  name: {{ .Release.Name }}-nginxweb
spec:
  ports:
  - name: {{ .Values.nginxweb.name }}-{{ .Values.env }}
    port: 80
    targetPort: 80
  selector:
    app: {{ .Values.nginxweb.name }}-{{ .Values.env }}