kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.storageClass.name }}
provisioner: kubernetes.io/azure-file
mountOptions:
  {{- range .Values.storageClass.mountOptions }}
  - {{ .  }}
  {{- end }}
parameters:
  skuName: {{ .Values.storageClass.skuName }}