replicas: 1
minimumMasterNodes: 1

# Enables security xpack features to have ES cluster and Kibana authentication
esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: true
    xpack.security.transport.ssl.enabled: true

# ES username and password are passed as env vars taken from secret
extraEnvs:
  - name: ELASTIC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: password
  - name: ELASTIC_USERNAME
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: username

# JVM options heap size settings
esJavaOpts: "-Xmx2g -Xms2g"

resources:
  requests:
    cpu: "100m"
    memory: "3Gi"
  limits:
    cpu: "1000m"
    memory: "3Gi"

# Adding persistent volume and specifying its storage class and size
persistence:
  enabled: true
  annotations: {}

volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "default"
  resources:
    requests:
      storage: 10Gi

ingress:
  enabled: true
  annotations:
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    # nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8"
  path: /
  hosts:
    - elastic.domain.com
  tls:
    - secretName: rapidssl-cert
      hosts:
        - elastic.domain.com
