# ES username and password are passed as env vars taken from secret
extraEnvs:
  - name: 'ELASTICSEARCH_USERNAME'
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: username
  - name: 'ELASTICSEARCH_PASSWORD'
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: password

# Kibana ingress parameters to use letencrypt certificates
ingress:
  enabled: true
  annotations:
    #cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
  path: /
  hosts:
    - kibana.domain.com
  tls:
    - secretName: rapidssl-cert
      hosts:
        - kibana.domain.com
